### PR TITLE
Added the ContactUs Page for Smooth Communication

### PR DESCRIPTION
**Pull request by Arpit529Srivastava**
issue 

This pull request introduces a new `ContactUs` page to the application, along with necessary routing and styling updates. The most important changes include adding the `ContactUs` component, updating the navigation bar for client-side routing, and adding new CSS styles for the `ContactUs` page.

### New `ContactUs` Page:

* [`src/App.js`](diffhunk://#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67R7): Imported the new `ContactUs` component and added a route for it.
* [`src/Components/ContactUs.js`](diffhunk://#diff-2529fb8f29e8700ce3db6b590b3efcdca78b8adfe1f2e79d920d047e77304507R1-R111): Created the `ContactUs` component with a form and FAQ section.
* [`src/Components/ContactUs.css`](diffhunk://#diff-aff24ccf2a38c22ec7517a3259fb2a6033b84b263c174c25c411c39b99dcb432R1-R43): Added CSS styles specifically for the `ContactUs` page.

### Navigation Bar Updates:

* [`src/Components/Navbar.js`](diffhunk://#diff-32f62f611b57db9e533531f51c5b306bbb9e8e1e734f9eadecd48785b5285bbeL45-R45): Updated the navigation bar to use `Link` for client-side routing, including a new link to the `ContactUs` page.

### CODE REVIEW

**Comment by Arpit529Srivastava** [comment]
@harshit1142 please review this also add the label ```hactoberfest-accepted``` also merge the pr 

thanku for the opportunity.

**Comment by harshit1142** [comment]
@Arpit529Srivastava Please do get assign before working on any issue

**Comment by Arpit529Srivastava** [comment]
@harshit1142 it was open for all that's why i started

**Comment by harshit1142** [comment]
@Arpit529Srivastava Add a product issue is " open to all "

**Comment by harshit1142** [comment]
@Arpit529Srivastava Take a latest update from main branch and only add Frequently Asked Questions

**Comment by harshit1142** [comment]
@Arpit529Srivastava any update ?

**Pull request closed without merging**
