### PR TITLE
Added About us page - issue #41

### PR DESCRIPTION
**Pull request by HemanthTigga**
Additionally shifted main part in App.js to Main.js file and also added routing

### CODE REVIEW

**Comment by HemanthTigga** [comment]
please review

**Comment by harshit1142** [comment]
@HemanthTigga add routing for Home too.

**Comment by HemanthTigga** [comment]
Sure

**Comment by HemanthTigga** [comment]
please check now

**Review by harshit1142 — APPROVED** [review]

**Pull request merged**
