### PR TITLE
Add sorting component

### PR DESCRIPTION
**Pull request by hendrahend**

### CODE REVIEW

**Comment by harshit1142** [comment]
@hendrahend ALSO,MAKE IT WORK .

**Comment by hendrahend** [comment]
i'll try

**Comment by hendrahend** [comment]
Screenshot (19)
Screenshot (20)

**Comment by harshit1142** [comment]
@hendrahend add only those which are working and also resize it and place at center ,below sell and wishlist

**Comment by hendrahend** [comment]
okay

**Comment by hendrahend** [comment]
Screenshot (22)

**Comment by hendrahend** [comment]
@harshit1142 done please check

**Review by harshit1142 — APPROVED** [review]

**Pull request merged**
